"""stock opportunity platform

Revision ID: 21ef0f0ea9fa
Revises: c4f2a91d0e77
Create Date: 2026-07-29 04:48:08.355913

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '21ef0f0ea9fa'
down_revision: str | None = 'c4f2a91d0e77'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_regimes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('regime', sa.String(length=30), nullable=False),
    sa.Column('session', sa.String(length=30), nullable=False),
    sa.Column('inputs_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_regimes_regime'), 'market_regimes', ['regime'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('risk_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_symbol'), 'news_items', ['symbol'], unique=False)
    op.create_table('provider_health',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_health_provider'), 'provider_health', ['provider'], unique=False)
    op.create_table('stock_scan_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('symbols_total', sa.Integer(), nullable=False),
    sa.Column('symbols_scanned', sa.Integer(), nullable=False),
    sa.Column('symbols_excluded', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_scan_runs_status'), 'stock_scan_runs', ['status'], unique=False)
    op.create_table('user_risk_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capital_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_risk_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('daily_loss_limit_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_run_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('numeric_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('exclusion_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['stock_scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_candidates_scan_run_id'), 'stock_candidates', ['scan_run_id'], unique=False)
    op.create_index(op.f('ix_stock_candidates_symbol'), 'stock_candidates', ['symbol'], unique=False)
    op.create_table('stock_opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_run_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('strategy_id', sa.String(length=40), nullable=False),
    sa.Column('market_regime', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quote_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_at_analysis', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('entry_from', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('entry_to', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('risk_reward', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data_fingerprint', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['stock_scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_opportunities_data_fingerprint'), 'stock_opportunities', ['data_fingerprint'], unique=False)
    op.create_index(op.f('ix_stock_opportunities_expires_at'), 'stock_opportunities', ['expires_at'], unique=False)
    op.create_index(op.f('ix_stock_opportunities_scan_run_id'), 'stock_opportunities', ['scan_run_id'], unique=False)
    op.create_index(op.f('ix_stock_opportunities_status'), 'stock_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_stock_opportunities_strategy_id'), 'stock_opportunities', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_stock_opportunities_symbol'), 'stock_opportunities', ['symbol'], unique=False)
    op.create_table('ai_analysis_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('data_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['stock_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_logs_data_fingerprint'), 'ai_analysis_logs', ['data_fingerprint'], unique=False)
    op.create_index(op.f('ix_ai_analysis_logs_symbol'), 'ai_analysis_logs', ['symbol'], unique=False)
    op.create_table('opportunity_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('entry_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('lowest_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target_1_hit', sa.Boolean(), nullable=False),
    sa.Column('target_2_hit', sa.Boolean(), nullable=False),
    sa.Column('stop_hit', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['stock_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_audits_opportunity_id'), 'opportunity_audits', ['opportunity_id'], unique=False)
    op.create_table('opportunity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['stock_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_events_opportunity_id'), 'opportunity_events', ['opportunity_id'], unique=False)
    op.create_table('opportunity_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('reached_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['stock_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_targets_opportunity_id'), 'opportunity_targets', ['opportunity_id'], unique=False)
    op.drop_table('audit_targets')
    op.drop_index('ix_snipe_option_signals_symbol', table_name='snipe_option_signals')
    op.drop_table('snipe_option_signals')
    op.drop_index('ix_option_contract_analyses_symbol', table_name='option_contract_analyses')
    op.drop_table('option_contract_analyses')
    op.drop_table('audit_results')
    op.drop_table('option_watchlist_events')
    op.drop_index('ix_option_watchlist_items_underlying_symbol', table_name='option_watchlist_items')
    op.drop_table('option_watchlist_items')
    op.drop_table('accuracy_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy_stats',
    sa.Column('regime', sa.VARCHAR(length=20), nullable=False),
    sa.Column('horizon_days', sa.INTEGER(), nullable=False),
    sa.Column('total_audited', sa.INTEGER(), nullable=False),
    sa.Column('avg_outcome', sa.NUMERIC(precision=4, scale=3), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('regime', 'horizon_days')
    )
    op.create_table('option_watchlist_events',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('watchlist_id', sa.CHAR(length=32), nullable=False),
    sa.Column('occurred_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status_tier', sa.INTEGER(), nullable=False),
    sa.Column('status_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('change_pct', sa.NUMERIC(precision=6, scale=2), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['option_watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_watchlist_items',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('underlying_symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('option_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('strike', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('expiry', sa.DATE(), nullable=False),
    sa.Column('reference_price', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('alert_threshold_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'5.0'"), nullable=False),
    sa.Column('invalidation_price', sa.NUMERIC(precision=12, scale=4), nullable=True),
    sa.Column('added_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('last_price', sa.NUMERIC(precision=12, scale=4), nullable=True),
    sa.Column('last_status_tier', sa.INTEGER(), nullable=True),
    sa.Column('last_status_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('last_message', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_option_watchlist_items_underlying_symbol', 'option_watchlist_items', ['underlying_symbol'], unique=False)
    op.create_table('audit_results',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('analysis_id', sa.CHAR(length=32), nullable=False),
    sa.Column('checked_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('horizon_days', sa.INTEGER(), nullable=False),
    sa.Column('price_at_check', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('max_high_since', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('min_low_since', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('scenario_realized', sa.VARCHAR(length=10), nullable=True),
    sa.Column('levels_touched', sqlite.JSON(), nullable=True),
    sa.Column('outcome_score', sa.NUMERIC(precision=4, scale=3), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_contract_analyses',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('requested_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('option_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('strike', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('expiry', sa.DATETIME(), nullable=False),
    sa.Column('contract_price_at_analysis', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('underlying_price', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('implied_volatility', sa.NUMERIC(precision=8, scale=6), nullable=False),
    sa.Column('analysis_json', sqlite.JSON(), nullable=False),
    sa.Column('extraction_confidence', sa.VARCHAR(length=10), nullable=False),
    sa.Column('vision_provider', sa.VARCHAR(length=30), nullable=False),
    sa.Column('total_cost_usd', sa.NUMERIC(precision=8, scale=5), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_option_contract_analyses_symbol', 'option_contract_analyses', ['symbol'], unique=False)
    op.create_table('snipe_option_signals',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('option_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('strike', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('expiry', sa.DATETIME(), nullable=False),
    sa.Column('underlying_price', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('bid', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('ask', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('mid_price', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('score', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('formula_version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('signal_json', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snipe_option_signals_symbol', 'snipe_option_signals', ['symbol'], unique=False)
    op.create_table('audit_targets',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('analysis_id', sa.CHAR(length=32), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('price_at_analysis', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('level_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('level_value', sa.NUMERIC(precision=12, scale=4), nullable=False),
    sa.Column('scenario', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_opportunity_targets_opportunity_id'), table_name='opportunity_targets')
    op.drop_table('opportunity_targets')
    op.drop_index(op.f('ix_opportunity_events_opportunity_id'), table_name='opportunity_events')
    op.drop_table('opportunity_events')
    op.drop_index(op.f('ix_opportunity_audits_opportunity_id'), table_name='opportunity_audits')
    op.drop_table('opportunity_audits')
    op.drop_index(op.f('ix_ai_analysis_logs_symbol'), table_name='ai_analysis_logs')
    op.drop_index(op.f('ix_ai_analysis_logs_data_fingerprint'), table_name='ai_analysis_logs')
    op.drop_table('ai_analysis_logs')
    op.drop_index(op.f('ix_stock_opportunities_symbol'), table_name='stock_opportunities')
    op.drop_index(op.f('ix_stock_opportunities_strategy_id'), table_name='stock_opportunities')
    op.drop_index(op.f('ix_stock_opportunities_status'), table_name='stock_opportunities')
    op.drop_index(op.f('ix_stock_opportunities_scan_run_id'), table_name='stock_opportunities')
    op.drop_index(op.f('ix_stock_opportunities_expires_at'), table_name='stock_opportunities')
    op.drop_index(op.f('ix_stock_opportunities_data_fingerprint'), table_name='stock_opportunities')
    op.drop_table('stock_opportunities')
    op.drop_index(op.f('ix_stock_candidates_symbol'), table_name='stock_candidates')
    op.drop_index(op.f('ix_stock_candidates_scan_run_id'), table_name='stock_candidates')
    op.drop_table('stock_candidates')
    op.drop_table('user_risk_settings')
    op.drop_index(op.f('ix_stock_scan_runs_status'), table_name='stock_scan_runs')
    op.drop_table('stock_scan_runs')
    op.drop_index(op.f('ix_provider_health_provider'), table_name='provider_health')
    op.drop_table('provider_health')
    op.drop_index(op.f('ix_news_items_symbol'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_market_regimes_regime'), table_name='market_regimes')
    op.drop_table('market_regimes')
    # ### end Alembic commands ###
