"""init schema

Revision ID: a11144e8b5c3
Revises: 
Create Date: 2026-07-14 08:59:18.004215

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a11144e8b5c3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy_stats',
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('total_audited', sa.Integer(), nullable=False),
    sa.Column('avg_outcome', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('regime', 'horizon_days')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('market_open', sa.Boolean(), nullable=False),
    sa.Column('data_provider', sa.String(length=30), nullable=False),
    sa.Column('llm_provider', sa.String(length=30), nullable=True),
    sa.Column('deterministic_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('report_text_ar', sa.Text(), nullable=True),
    sa.Column('report_text_en', sa.Text(), nullable=True),
    sa.Column('llm_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('llm_output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('cache_source_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['cache_source_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_symbol'), 'analyses', ['symbol'], unique=False)
    op.create_table('cache_entries',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_cache_entries_expires_at'), 'cache_entries', ['expires_at'], unique=False)
    op.create_table('cost_limits',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('daily_cap_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('monthly_cap_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('kill_switch_on', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('price_at_check', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_high_since', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('min_low_since', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('scenario_realized', sa.String(length=10), nullable=True),
    sa.Column('levels_touched', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('outcome_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('price_at_analysis', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('level_type', sa.String(length=20), nullable=False),
    sa.Column('level_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('scenario', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_ledger',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_ledger')
    op.drop_table('audit_targets')
    op.drop_table('audit_results')
    op.drop_table('cost_limits')
    op.drop_index(op.f('ix_cache_entries_expires_at'), table_name='cache_entries')
    op.drop_table('cache_entries')
    op.drop_index(op.f('ix_analyses_symbol'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('accuracy_stats')
    # ### end Alembic commands ###
