"""add option_contract_analyses table

Revision ID: aa401616d6ae
Revises: a11144e8b5c3
Create Date: 2026-07-14 11:20:04.726916

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa401616d6ae'
down_revision: str | None = 'a11144e8b5c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_contract_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('contract_price_at_analysis', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('underlying_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('implied_volatility', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('analysis_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('extraction_confidence', sa.String(length=10), nullable=False),
    sa.Column('vision_provider', sa.String(length=30), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_contract_analyses_symbol'), 'option_contract_analyses', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_contract_analyses_symbol'), table_name='option_contract_analyses')
    op.drop_table('option_contract_analyses')
    # ### end Alembic commands ###
