"""Curated list of well-known US-listed tickers for the web UI's client-side autocomplete
(task: symbol autocomplete). Not a live/official S&P 500 constituent feed (index
membership changes over time and this app has no external symbol-lookup API) — just a
broad, hand-curated set of large caps plus popular retail-traded names, sufficient for
"type a few letters, see suggestions" without any network call.
"""
from __future__ import annotations

US_SYMBOLS: list[dict[str, str]] = [
    {"symbol": "AAPL", "name": "Apple Inc."},
    {"symbol": "MSFT", "name": "Microsoft Corp."},
    {"symbol": "GOOGL", "name": "Alphabet Inc. (Class A)"},
    {"symbol": "GOOG", "name": "Alphabet Inc. (Class C)"},
    {"symbol": "AMZN", "name": "Amazon.com Inc."},
    {"symbol": "NVDA", "name": "NVIDIA Corp."},
    {"symbol": "META", "name": "Meta Platforms Inc."},
    {"symbol": "TSLA", "name": "Tesla Inc."},
    {"symbol": "BRK.B", "name": "Berkshire Hathaway (Class B)"},
    {"symbol": "AVGO", "name": "Broadcom Inc."},
    {"symbol": "LLY", "name": "Eli Lilly and Co."},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co."},
    {"symbol": "V", "name": "Visa Inc."},
    {"symbol": "MA", "name": "Mastercard Inc."},
    {"symbol": "UNH", "name": "UnitedHealth Group Inc."},
    {"symbol": "XOM", "name": "Exxon Mobil Corp."},
    {"symbol": "COST", "name": "Costco Wholesale Corp."},
    {"symbol": "HD", "name": "Home Depot Inc."},
    {"symbol": "PG", "name": "Procter & Gamble Co."},
    {"symbol": "JNJ", "name": "Johnson & Johnson"},
    {"symbol": "ABBV", "name": "AbbVie Inc."},
    {"symbol": "NFLX", "name": "Netflix Inc."},
    {"symbol": "CRM", "name": "Salesforce Inc."},
    {"symbol": "BAC", "name": "Bank of America Corp."},
    {"symbol": "KO", "name": "Coca-Cola Co."},
    {"symbol": "AMD", "name": "Advanced Micro Devices Inc."},
    {"symbol": "PEP", "name": "PepsiCo Inc."},
    {"symbol": "WMT", "name": "Walmart Inc."},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc."},
    {"symbol": "CSCO", "name": "Cisco Systems Inc."},
    {"symbol": "MCD", "name": "McDonald's Corp."},
    {"symbol": "ACN", "name": "Accenture plc"},
    {"symbol": "ABT", "name": "Abbott Laboratories"},
    {"symbol": "ADBE", "name": "Adobe Inc."},
    {"symbol": "ORCL", "name": "Oracle Corp."},
    {"symbol": "DIS", "name": "Walt Disney Co."},
    {"symbol": "PFE", "name": "Pfizer Inc."},
    {"symbol": "INTC", "name": "Intel Corp."},
    {"symbol": "QCOM", "name": "Qualcomm Inc."},
    {"symbol": "IBM", "name": "IBM Corp."},
    {"symbol": "TXN", "name": "Texas Instruments Inc."},
    {"symbol": "CAT", "name": "Caterpillar Inc."},
    {"symbol": "GE", "name": "General Electric Co."},
    {"symbol": "NKE", "name": "Nike Inc."},
    {"symbol": "VZ", "name": "Verizon Communications Inc."},
    {"symbol": "T", "name": "AT&T Inc."},
    {"symbol": "PM", "name": "Philip Morris International"},
    {"symbol": "UPS", "name": "United Parcel Service Inc."},
    {"symbol": "LOW", "name": "Lowe's Companies Inc."},
    {"symbol": "HON", "name": "Honeywell International Inc."},
    {"symbol": "AMGN", "name": "Amgen Inc."},
    {"symbol": "SBUX", "name": "Starbucks Corp."},
    {"symbol": "BA", "name": "Boeing Co."},
    {"symbol": "GS", "name": "Goldman Sachs Group Inc."},
    {"symbol": "MS", "name": "Morgan Stanley"},
    {"symbol": "BLK", "name": "BlackRock Inc."},
    {"symbol": "SPGI", "name": "S&P Global Inc."},
    {"symbol": "AXP", "name": "American Express Co."},
    {"symbol": "C", "name": "Citigroup Inc."},
    {"symbol": "WFC", "name": "Wells Fargo & Co."},
    {"symbol": "MU", "name": "Micron Technology Inc."},
    {"symbol": "ISRG", "name": "Intuitive Surgical Inc."},
    {"symbol": "BKNG", "name": "Booking Holdings Inc."},
    {"symbol": "GILD", "name": "Gilead Sciences Inc."},
    {"symbol": "ADP", "name": "Automatic Data Processing Inc."},
    {"symbol": "MDT", "name": "Medtronic plc"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals Inc."},
    {"symbol": "REGN", "name": "Regeneron Pharmaceuticals Inc."},
    {"symbol": "PANW", "name": "Palo Alto Networks Inc."},
    {"symbol": "NOW", "name": "ServiceNow Inc."},
    {"symbol": "INTU", "name": "Intuit Inc."},
    {"symbol": "AMAT", "name": "Applied Materials Inc."},
    {"symbol": "LRCX", "name": "Lam Research Corp."},
    {"symbol": "MRK", "name": "Merck & Co."},
    {"symbol": "CVX", "name": "Chevron Corp."},
    {"symbol": "COP", "name": "ConocoPhillips"},
    {"symbol": "SLB", "name": "Schlumberger NV"},
    {"symbol": "DE", "name": "Deere & Co."},
    {"symbol": "LMT", "name": "Lockheed Martin Corp."},
    {"symbol": "RTX", "name": "RTX Corp."},
    {"symbol": "NOC", "name": "Northrop Grumman Corp."},
    {"symbol": "UNP", "name": "Union Pacific Corp."},
    {"symbol": "FDX", "name": "FedEx Corp."},
    {"symbol": "TGT", "name": "Target Corp."},
    {"symbol": "DHR", "name": "Danaher Corp."},
    {"symbol": "PYPL", "name": "PayPal Holdings Inc."},
    {"symbol": "SQ", "name": "Block Inc."},
    {"symbol": "SHOP", "name": "Shopify Inc."},
    {"symbol": "UBER", "name": "Uber Technologies Inc."},
    {"symbol": "LYFT", "name": "Lyft Inc."},
    {"symbol": "ABNB", "name": "Airbnb Inc."},
    {"symbol": "COIN", "name": "Coinbase Global Inc."},
    {"symbol": "SNOW", "name": "Snowflake Inc."},
    {"symbol": "PLTR", "name": "Palantir Technologies Inc."},
    {"symbol": "NET", "name": "Cloudflare Inc."},
    {"symbol": "DDOG", "name": "Datadog Inc."},
    {"symbol": "CRWD", "name": "CrowdStrike Holdings Inc."},
    {"symbol": "ZS", "name": "Zscaler Inc."},
    {"symbol": "MDB", "name": "MongoDB Inc."},
    {"symbol": "TEAM", "name": "Atlassian Corp."},
    {"symbol": "WDAY", "name": "Workday Inc."},
    {"symbol": "ROKU", "name": "Roku Inc."},
    {"symbol": "SPOT", "name": "Spotify Technology SA"},
    {"symbol": "RBLX", "name": "Roblox Corp."},
    {"symbol": "DASH", "name": "DoorDash Inc."},
    {"symbol": "PINS", "name": "Pinterest Inc."},
    {"symbol": "SNAP", "name": "Snap Inc."},
    {"symbol": "TWLO", "name": "Twilio Inc."},
    {"symbol": "ZM", "name": "Zoom Video Communications Inc."},
    {"symbol": "DOCU", "name": "DocuSign Inc."},
    {"symbol": "OKTA", "name": "Okta Inc."},
    {"symbol": "PATH", "name": "UiPath Inc."},
    {"symbol": "RIVN", "name": "Rivian Automotive Inc."},
    {"symbol": "LCID", "name": "Lucid Group Inc."},
    {"symbol": "F", "name": "Ford Motor Co."},
    {"symbol": "GM", "name": "General Motors Co."},
    {"symbol": "NIO", "name": "NIO Inc."},
    {"symbol": "XPEV", "name": "XPeng Inc."},
    {"symbol": "LI", "name": "Li Auto Inc."},
    {"symbol": "GME", "name": "GameStop Corp."},
    {"symbol": "AMC", "name": "AMC Entertainment Holdings Inc."},
    {"symbol": "BB", "name": "BlackBerry Ltd."},
    {"symbol": "NOK", "name": "Nokia Corp."},
    {"symbol": "SOFI", "name": "SoFi Technologies Inc."},
    {"symbol": "HOOD", "name": "Robinhood Markets Inc."},
    {"symbol": "AFRM", "name": "Affirm Holdings Inc."},
    {"symbol": "UPST", "name": "Upstart Holdings Inc."},
    {"symbol": "MSTR", "name": "MicroStrategy Inc."},
    {"symbol": "MARA", "name": "MARA Holdings Inc."},
    {"symbol": "RIOT", "name": "Riot Platforms Inc."},
    {"symbol": "CVNA", "name": "Carvana Co."},
    {"symbol": "DKNG", "name": "DraftKings Inc."},
    {"symbol": "BABA", "name": "Alibaba Group Holding Ltd."},
    {"symbol": "PDD", "name": "PDD Holdings Inc."},
    {"symbol": "JD", "name": "JD.com Inc."},
    {"symbol": "SE", "name": "Sea Ltd."},
    {"symbol": "MELI", "name": "MercadoLibre Inc."},
    {"symbol": "TSM", "name": "Taiwan Semiconductor Manufacturing"},
    {"symbol": "ASML", "name": "ASML Holding NV"},
    {"symbol": "ARM", "name": "Arm Holdings plc"},
    {"symbol": "SMCI", "name": "Super Micro Computer Inc."},
    {"symbol": "DELL", "name": "Dell Technologies Inc."},
    {"symbol": "HPQ", "name": "HP Inc."},
    {"symbol": "PARA", "name": "Paramount Global"},
    {"symbol": "WBD", "name": "Warner Bros. Discovery Inc."},
    {"symbol": "CMCSA", "name": "Comcast Corp."},
    {"symbol": "CHTR", "name": "Charter Communications Inc."},
    {"symbol": "TMUS", "name": "T-Mobile US Inc."},
    {"symbol": "MO", "name": "Altria Group Inc."},
    {"symbol": "KHC", "name": "Kraft Heinz Co."},
    {"symbol": "GIS", "name": "General Mills Inc."},
    {"symbol": "CL", "name": "Colgate-Palmolive Co."},
    {"symbol": "KMB", "name": "Kimberly-Clark Corp."},
    {"symbol": "MDLZ", "name": "Mondelez International Inc."},
    {"symbol": "STZ", "name": "Constellation Brands Inc."},
    {"symbol": "EL", "name": "Estee Lauder Companies Inc."},
    {"symbol": "CMG", "name": "Chipotle Mexican Grill Inc."},
    {"symbol": "YUM", "name": "Yum! Brands Inc."},
    {"symbol": "DPZ", "name": "Domino's Pizza Inc."},
    {"symbol": "LULU", "name": "Lululemon Athletica Inc."},
    {"symbol": "ETSY", "name": "Etsy Inc."},
    {"symbol": "EBAY", "name": "eBay Inc."},
    {"symbol": "BIDU", "name": "Baidu Inc."},
    {"symbol": "SIRI", "name": "Sirius XM Holdings Inc."},
    {"symbol": "PYPL", "name": "PayPal Holdings Inc."},
    {"symbol": "FIS", "name": "Fidelity National Information Services"},
    {"symbol": "FISV", "name": "Fiserv Inc."},
    {"symbol": "PGR", "name": "Progressive Corp."},
    {"symbol": "TRV", "name": "Travelers Companies Inc."},
    {"symbol": "ALL", "name": "Allstate Corp."},
    {"symbol": "MET", "name": "MetLife Inc."},
    {"symbol": "PRU", "name": "Prudential Financial Inc."},
    {"symbol": "AIG", "name": "American International Group Inc."},
    {"symbol": "SCHW", "name": "Charles Schwab Corp."},
    {"symbol": "USB", "name": "U.S. Bancorp"},
    {"symbol": "PNC", "name": "PNC Financial Services Group"},
    {"symbol": "TFC", "name": "Truist Financial Corp."},
    {"symbol": "COF", "name": "Capital One Financial Corp."},
    {"symbol": "SPY", "name": "SPDR S&P 500 ETF Trust"},
    {"symbol": "QQQ", "name": "Invesco QQQ Trust (Nasdaq-100)"},
    {"symbol": "DIA", "name": "SPDR Dow Jones Industrial Average ETF"},
    {"symbol": "IWM", "name": "iShares Russell 2000 ETF"},
    {"symbol": "VOO", "name": "Vanguard S&P 500 ETF"},
    {"symbol": "VTI", "name": "Vanguard Total Stock Market ETF"},
    {"symbol": "GLD", "name": "SPDR Gold Shares"},
    {"symbol": "SLV", "name": "iShares Silver Trust"},
    {"symbol": "USO", "name": "United States Oil Fund"},
    {"symbol": "TLT", "name": "iShares 20+ Year Treasury Bond ETF"},
    {"symbol": "XLE", "name": "Energy Select Sector SPDR Fund"},
    {"symbol": "XLF", "name": "Financial Select Sector SPDR Fund"},
    {"symbol": "XLK", "name": "Technology Select Sector SPDR Fund"},
    {"symbol": "ARKK", "name": "ARK Innovation ETF"},
    {"symbol": "VIX", "name": "CBOE Volatility Index"},
]

# Focused universe for the Snipe flow: actively traded option underlyings. Contract-level
# spread, open-interest, premium, Greeks, and expiry gates still decide what is displayed.
SNIPE_OPTION_UNIVERSE = {
    "SPY", "QQQ", "IWM", "DIA", "TLT", "GLD", "SLV", "USO", "XLE", "XLF", "XLK", "ARKK",
    "AAPL", "NVDA", "TSLA", "AMD", "AMZN", "META", "MSFT", "GOOGL", "NFLX", "AVGO", "MU",
    "INTC", "PLTR", "COIN", "MSTR", "MARA", "RIOT", "SOFI", "BAC", "JPM", "C", "WFC", "DIS",
    "BA", "NKE", "PFE", "XOM", "CVX", "UNH", "LLY", "SHOP", "UBER", "SNAP", "PYPL",
}
