"""Curated US symbols for local, zero-cost autocomplete."""

US_SYMBOLS: tuple[tuple[str, str], ...] = (
    ("AAPL", "Apple"),
    ("ABBV", "AbbVie"),
    ("ABNB", "Airbnb"),
    ("ACHR", "Archer Aviation"),
    ("ADBE", "Adobe"),
    ("AMD", "Advanced Micro Devices"),
    ("AMGN", "Amgen"),
    ("AMZN", "Amazon"),
    ("ARM", "Arm Holdings"),
    ("AVGO", "Broadcom"),
    ("AXP", "American Express"),
    ("BA", "Boeing"),
    ("BABA", "Alibaba"),
    ("BAC", "Bank of America"),
    ("BBAI", "BigBear.ai"),
    ("BB", "BlackBerry"),
    ("BLK", "BlackRock"),
    ("C", "Citigroup"),
    ("CAT", "Caterpillar"),
    ("CLSK", "CleanSpark"),
    ("COIN", "Coinbase"),
    ("COST", "Costco"),
    ("CRM", "Salesforce"),
    ("CRWD", "CrowdStrike"),
    ("CVX", "Chevron"),
    ("DIS", "Walt Disney"),
    ("DKNG", "DraftKings"),
    ("F", "Ford"),
    ("GME", "GameStop"),
    ("GOOG", "Alphabet Class C"),
    ("GOOGL", "Alphabet Class A"),
    ("GRAB", "Grab Holdings"),
    ("GS", "Goldman Sachs"),
    ("HD", "Home Depot"),
    ("HIMS", "Hims & Hers"),
    ("HOOD", "Robinhood"),
    ("IBM", "IBM"),
    ("INTC", "Intel"),
    ("IONQ", "IonQ"),
    ("JNJ", "Johnson & Johnson"),
    ("JOBY", "Joby Aviation"),
    ("JPM", "JPMorgan Chase"),
    ("KO", "Coca-Cola"),
    ("LCID", "Lucid"),
    ("LLY", "Eli Lilly"),
    ("LMT", "Lockheed Martin"),
    ("LUNR", "Intuitive Machines"),
    ("MA", "Mastercard"),
    ("MARA", "MARA Holdings"),
    ("META", "Meta Platforms"),
    ("MRK", "Merck"),
    ("MRNA", "Moderna"),
    ("MS", "Morgan Stanley"),
    ("MSFT", "Microsoft"),
    ("MU", "Micron"),
    ("NFLX", "Netflix"),
    ("NIO", "NIO"),
    ("NKE", "Nike"),
    ("NOC", "Northrop Grumman"),
    ("NOW", "ServiceNow"),
    ("NVDA", "NVIDIA"),
    ("ORCL", "Oracle"),
    ("PANW", "Palo Alto Networks"),
    ("PEP", "PepsiCo"),
    ("PFE", "Pfizer"),
    ("PLTR", "Palantir"),
    ("PLUG", "Plug Power"),
    ("PYPL", "PayPal"),
    ("QCOM", "Qualcomm"),
    ("QQQ", "Invesco QQQ"),
    ("QUBT", "Quantum Computing"),
    ("RGTI", "Rigetti Computing"),
    ("RIOT", "Riot Platforms"),
    ("RIVN", "Rivian"),
    ("RKLB", "Rocket Lab"),
    ("SBUX", "Starbucks"),
    ("SHOP", "Shopify"),
    ("SMCI", "Super Micro Computer"),
    ("SNAP", "Snap"),
    ("SOFI", "SoFi Technologies"),
    ("SOUN", "SoundHound AI"),
    ("SPY", "SPDR S&P 500 ETF"),
    ("T", "AT&T"),
    ("TGT", "Target"),
    ("TLRY", "Tilray Brands"),
    ("TMC", "TMC the metals company"),
    ("TSLA", "Tesla"),
    ("TSM", "Taiwan Semiconductor"),
    ("UBER", "Uber"),
    ("UNH", "UnitedHealth"),
    ("V", "Visa"),
    ("VZ", "Verizon"),
    ("WFC", "Wells Fargo"),
    ("WMT", "Walmart"),
    ("XOM", "Exxon Mobil"),
)


def autocomplete_payload() -> list[dict[str, str]]:
    return [{"symbol": symbol, "name": name} for symbol, name in US_SYMBOLS]
